### PR TITLE
Relocate code for Ascend logo to Inference section

### PR DESCRIPTION
**Pull request by hannibalhuang**
The previous PR #99 was added to the wrong section on the webpage
Signed-off-by: Zhipeng Huang <zhipengh512@gmail.com>

### CODE REVIEW

**Review by AlexandreEichenberger — APPROVED** [review]
LGTM, double checked the new link `https://www.hiascend.com/en/software/modelzoo#onnx` and it worked for me

**Comment by hannibalhuang** [comment]
also ping @prasanthpul

**Comment by prasanthpul** [comment]
When I follow the link it goes to a model zoo.. can you clarify why it shouldnt be under model zoo section?

**Review by andife — APPROVED** [review]

**Comment by andife** [comment]
could be reasonable https://onnxruntime.ai/docs/execution-providers/community-maintained/CANN-ExecutionProvider.html

**Pull request merged**
