### PR TITLE
Add catboost logo

### PR DESCRIPTION
**Pull request by nikitxskv**
The attached CatBoost logo can be used to be displayed on the onnx.ai website as well as in presentations showing ONNX Member Companies.
Links should point to https://catboost.ai/docs/concepts/apply-onnx-ml.html?lang=en

### CODE REVIEW

**Comment by prasanthpul** [comment]
Thanks - will add this to the supported tools page - https://onnx.ai/supported-tools.html

Would you like Yandex logo on the main page - https://onnx.ai?

**Comment by nikitxskv** [comment]
@prasanthpul 
Yes, that would be great!
I added the Yandex logo.
Thanks!

**Comment by nikitxskv** [comment]
> We need the logo files to be a specific size (250x84). I'm happy to do the resizing and updating the HTML for you if you move your source image files to the assets folder.

Done. Thank you very much!

**Comment by nikitxskv** [comment]
Hi @prasanthpul!
Should I do something else to merge this pull request?

**Comment by prasanthpul** [comment]
@nikitxskv I've added the logos to the site in #69. However we still need to merge this PR too for completeness.

I was trying to remove the changes in support-tools.html but inadvertently deleted the whole file in your branch. I'm apparently able to do that but don't have permissions to fix it. If you can rebase your branch so that this PR only contains the two image files you added to assets/, I can merge it.

**Comment by nikitxskv** [comment]
@prasanthpul Done!

**Pull request merged**
