### PR TITLE
Maxar logo upload to homepage 

### PR DESCRIPTION
**Pull request by nmetzgar**
Our product Deepcore uses ONNX as a means to run computer vision algorithms agains geospatial imagery. The hyperlink should go to www.deepcore.io

### CODE REVIEW

**Comment by nmetzgar** [comment]
Is there any update on this? I am not suer how long this usually takes to get put on the site. Thanks!

**Comment by prasanthpul** [comment]
sorry for the delay. we are in the process of updating the website and hoped to include this in that. it's taking a bit longer, so I will see if we can update the existing site. @brucejlin1 can you help?

**Comment by nmetzgar** [comment]
Hey Prasanth, just checking in on this. We are trying to time this with the roll out of a few blog posts. Thanks much

**Comment by brucejlin1** [comment]
@nmetzgar apologies for the delay, Maxar has been added to the homepage logo cloud.

**Comment by nmetzgar** [comment]
> @nmetzgar apologies for the delay, Maxar has been added to the homepage logo cloud.

Thanks, Bruce!

**Pull request merged**
