### PR TITLE
Updated Getting started

### PR DESCRIPTION
**Pull request by jspisak**
Installation and tutorials now reflect that ONNX is natively supported in Caffe2.

### CODE REVIEW

**Comment by jspisak** [comment]
@prasanthpul Can you please merge this change?

**Comment by prasanthpul** [comment]
@jspisak I merged it, but I can't get pip install caffe2 to work on windows.. Can the team fix that?

**Comment by yinghai** [comment]
I see. We should probably direct user to https://caffe2.ai/docs/getting-started.html instead. @jspisak Different platforms have different ways of installing Caffe2.

**Comment by jspisak** [comment]
@prasanthpul @yinghai  Cool, let me make that change to make it more generic.

**Pull request merged**
