### PR TITLE
update logo of PaddlePaddle

### PR DESCRIPTION
**Pull request by Channingss**
update logo of PaddlePaddle.

### CODE REVIEW

**Review by prasanthpul — CHANGES_REQUESTED** [review]
Can you replace this file (https://github.com/onnx/onnx.github.io/blob/master/assets/PaddlePaddle_510x120.png) instead? please ensure the background is transparent.

**Comment by Channingss** [comment]
> Can you replace this file (https://github.com/onnx/onnx.github.io/blob/master/assets/PaddlePaddle_510x120.png) instead? please ensure the background is transparent.

Excuse me， resolution of this logo must be 510x120?

**Comment by Channingss** [comment]
> Can you replace this file (https://github.com/onnx/onnx.github.io/blob/master/assets/PaddlePaddle_510x120.png) instead? please ensure the background is transparent.

Done

**Comment by tizhou86** [comment]
@prasanthpul here is the updated logo, can you review and merge this pr? thanks!

**Comment by prasanthpul** [comment]
Handled in https://github.com/onnx/onnx.github.io/pull/90

**Pull request closed without merging**
