### PR TITLE
add onnx 1.12.0 release news

### PR DESCRIPTION
**Pull request by liqunfu**
Signed-off-by: Liqun Fu <liqfu@microsoft.com>

### CODE REVIEW

**Comment by liqunfu** [comment]
@prasanthpul @AlexandreEichenberger , please review. 
Thanks!
Liqun

**Comment by AlexandreEichenberger** [comment]
LGTM I wonder if we should not delay this PR for another week so as to leave the announcement for the community meet which is June 24. What do folks think?

**Comment by AlexandreEichenberger** [comment]
I can see it go either ways

**Comment by liqunfu** [comment]
Thank you @AlexandreEichenberger , Will check with @prasanthpul and other folks.

**Pull request merged**
